/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.hexlet;

import io.hexlet.states.ClockState;
import io.hexlet.states.State;

public class AlarmClock {

    private State state;

    private int hours;
    private int minutes;

    private int alarmHours;
    private int alarmMinutes;

    private boolean alarmOn;


    public AlarmClock() {
        this.state = new ClockState();
        this.hours = 12;
        this.minutes = 0;
        this.alarmHours = 6;
        this.alarmMinutes = 0;
    }

    public void tick() {
        minutes++;
        if (minutes == 60) {
            hours++;
            minutes = 0;
        }
        if (hours == 24) {
            hours =0;
        }
    }

    public boolean isAlarmOn() {
        return alarmOn;
    }

    public boolean isAlarmTime() {
        return minutes == alarmMinutes && hours == alarmHours;
    }
    public int getMinutes() {
        return this.minutes;
    }

    public int getHours() {
        return this.hours;
    }

    public int getAlarmMinutes() {
        return this.alarmMinutes;
    }

    public int getAlarmHours() {
        return this.alarmHours;
    }

    public String getCurrentMode() {
        return this.state.getStateName();
    }



    public void clickMode() {
        state.clickMode(this);
    }

    public void setState(State state) {
        this.state = state;
    }

























}
