/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.hexlet;

import io.hexlet.states.BellState;
import io.hexlet.states.ClockState;
import io.hexlet.states.State;

public final class AlarmClock {

    private State state;

    private int hours;
    private int minutes;

    private int alarmHours;
    private int alarmMinutes;

    private boolean alarmOn;


    public AlarmClock() {
        this.state = new ClockState();
        this.hours = 12;
        this.minutes = 0;
        this.alarmHours = 6;
        this.alarmMinutes = 0;
    }

    public void tick() {
        incrementMinutes();
        if (minutes == 0) {
            incrementHours();
        }
        if (state instanceof BellState) {
            this.setState(new ClockState());
        }
        if (isAlarmOn() && isAlarmTime()) {
            this.setState(new BellState());
        }
    }

    public boolean isAlarmOn() {
        return alarmOn;
    }

    public boolean isAlarmTime() {
        return minutes == alarmMinutes && hours == alarmHours;
    }
    public int getMinutes() {
        return this.minutes;
    }

    public int getHours() {
        return this.hours;
    }

    public int getAlarmMinutes() {
        return this.alarmMinutes;
    }

    public int getAlarmHours() {
        return this.alarmHours;
    }

    public String getCurrentMode() {
        return this.state.getStateName();
    }

    public void clickMode() {
        state.clickMode(this);
    }

    public void setState(State state) {
        this.state = state;
    }

    public void longClickMode() {
        alarmOn = !alarmOn;
    }

    public void clickH() {
        this.state.clickH(this);
    }

    public void clickM() {
        this.state.clickM(this);
    }


    public void incrementHours() {
        hours = ++hours == 24 ? 0 : hours;
    }

    public void incrementMinutes() {
        minutes = ++minutes == 60 ? 0 : minutes;
    }

    public void incrementAlarmHours() {
        alarmHours = ++alarmHours == 24 ? 0 : alarmHours;
    }

    public void incrementAlarmMinutes() {
        alarmMinutes = ++alarmMinutes == 60 ? 0 : alarmMinutes;
    }
}
